[package]
name = "backup-local"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
backup-application = { path = "../backup-application" }
backup-crypto = { path = "../backup-crypto" }
backup-domain = { path = "../backup-domain" }
backup-inventory = { path = "../backup-inventory" }
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
